[workspace]

members = [
    "projects/cmd/rgrep",
    "projects/cmd/server",
    "projects/cmd/city-pop",

    "projects/lib/segment_io",
    "projects/lib/lsmt",

    "examples/serde_examples",
    "examples/env_examples",
    "examples/fs_examples",
]

exclude = [
    "playground",
]
