[workspace]

members = [
    "projects/rgrep",
    "projects/server",
    "projects/city-pop",
    "projects/pingcap/talent-plan/kvs",

    "examples/serde_examples",
]

exclude = [
    "playground",
]
