[workspace]

members = [
    "projects/cmd/rgrep",
    "projects/cmd/server",
    "projects/cmd/city-pop",
    "projects/cmd/pingcap/talent-plan/kvs",

    "projects/lib/buff_io",

    "examples/serde_examples",
]

exclude = [
    "playground",
]
